(part "IPT034N15NM6ATMA1"
    (packageRef "IAUT150N10S5N035ATMA1")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "S_3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "S_4") (portType INOUT))
        (port "6" (symbPinId 6) (portName "S_5") (portType INOUT))
        (port "7" (symbPinId 7) (portName "S_6") (portType INOUT))
        (port "8" (symbPinId 8) (portName "S_7") (portType INOUT))
        (port "9" (symbPinId 9) (portName "D_1") (portType INOUT))
        (port "10" (symbPinId 10) (portName "D_2") (portType INOUT))
        (port "11" (symbPinId 11) (portName "D_3") (portType INOUT))
        (port "12" (symbPinId 12) (portName "S_8") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "IPT034N15NM6ATMA1")
    (property "Mouser_Part_Number" "726-IPT034N15NM6ATMA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/IPT034N15NM6ATMA1?qs=7%2F6SraaimPSH5LUgDMi%2FsQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "MOSFETs OptiMOS 6 power MOSFET 150 V normal level in TOLL package")
    (property "Datasheet_Link" "https://www.infineon.com/assets/row/public/documents/24/49/infineon-ipt034n15nm6-datasheet-en.pdf")
    (property "symbolName1" "IPT034N15NM6ATMA1")
)
