(part "SS3P4-M3_85A"
    (packageRef "SS3P4M385A")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SS3P4-M3/85A")
    (property "Mouser_Part_Number" "625-SS3P4-M3/85A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-General-Semiconductor/SS3P4-M3-85A?qs=HSPD0Bff7ibKviouswwnaQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "High Current Density Surface-Mount Schottky Rectifiers")
    (property "Datasheet_Link" "https://www.vishay.com/docs/88954/ss3p4.pdf")
    (property "symbolName1" "SS3P4-M3_85A")
)
