(part "MSS1P4-M3_89A"
    (packageRef "MICROSMP")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "MSS1P4-M3/89A")
    (property "Mouser_Part_Number" "625-MSS1P4-M3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-General-Semiconductor/MSS1P4-M3-89A?qs=fLSHF8TigmUkO6GnwlXAxQ%3D%3D")
    (property "Arrow_Part_Number" "MSS1P4-M3/89A")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/mss1p4-m389a/vishay?utm_currency=USD&region=europe")
    (property "Description" "Vishay MSS1P4-M3/89A SMT Schottky Diode, 40V 1A, 2-Pin uSMP")
    (property "Datasheet_Link" "https://www.vishay.com/docs/89019/mss1p4.pdf")
    (property "symbolName1" "MSS1P4-M3_89A")
)
