(part "1705469"
    (packageRef "1705469")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Phoenix Contact")
    (property "Manufacturer_Part_Number" "1705469")
    (property "Mouser_Part_Number" "651-1705469")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Phoenix-Contact/1705469?qs=qgZcrvoyHAeKr1p0qncEog%3D%3D")
    (property "Arrow_Part_Number" "1705469")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/1705469/phoenix-contact?utm_currency=USD&region=nac")
    (property "Description" "Fixed Terminal Blocks 2P 5.08mm 40DEG")
    (property "Datasheet_Link" "https://www.phoenixcontact.com/en-us/products/printed-circuit-board-terminal-smkds-25-2-508-1705469?type=pdf")
    (property "symbolName1" "1705469")
)
