(part "2EDL23N06PJ"
    (packageRef "SOIC127P600X175-14N")
    (interface
        (port "1" (symbPinId 1) (portName "VDD") (portType INOUT))
        (port "2" (symbPinId 2) (portName "HIN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "LIN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EN-/FLT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND") (portType INOUT))
        (port "6" (symbPinId 6) (portName "PGND") (portType INOUT))
        (port "7" (symbPinId 7) (portName "LO") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC_1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "NC_2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VS") (portType INOUT))
        (port "11" (symbPinId 11) (portName "HO") (portType INOUT))
        (port "12" (symbPinId 12) (portName "VB") (portType INOUT))
        (port "13" (symbPinId 13) (portName "NC_3") (portType INOUT))
        (port "14" (symbPinId 14) (portName "NC_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "2EDL23N06PJ")
    (property "Mouser_Part_Number" "726-2EDL23N06PJ")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/2EDL23N06PJ?qs=61g%252BPyeGH21MM1hsJUEj5A%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Infineon 2EDL23N06PJ, MOSFET Power Driver")
    (property "Datasheet_Link" "https://www.mouser.in/datasheet/2/196/Infineon_2EDL23x06xx_DataSheet_v02_08_EN-776784.pdf")
    (property "symbolName1" "2EDL23N06PJ")
)
