(part "CKSR_6-NP"
    (packageRef "CKSR6NP")
    (interface
        (port "2" (symbPinId 1) (portName "IN_1") (portType INOUT))
        (port "3" (symbPinId 2) (portName "IN_2") (portType INOUT))
        (port "4" (symbPinId 3) (portName "IN_3") (portType INOUT))
        (port "5" (symbPinId 4) (portName "IN_4") (portType INOUT))
        (port "6" (symbPinId 5) (portName "OUT_1") (portType INOUT))
        (port "7" (symbPinId 6) (portName "OUT_2") (portType INOUT))
        (port "8" (symbPinId 7) (portName "OUT_3") (portType INOUT))
        (port "9" (symbPinId 8) (portName "OUT_4") (portType INOUT))
        (port "11" (symbPinId 9) (portName "VREF") (portType INOUT))
        (port "12" (symbPinId 10) (portName "VOUT") (portType INOUT))
        (port "13" (symbPinId 11) (portName "GND") (portType INOUT))
        (port "14" (symbPinId 12) (portName "UC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "LEM")
    (property "Manufacturer_Part_Number" "CKSR 6-NP")
    (property "Mouser_Part_Number" "61-CKSR6-NP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/LEM/CKSR-6-NP?qs=Vi0JKjFBtYnGKGFrcOKHHQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Current Transducer 6A, Low Drift +5V Vs")
    (property "Datasheet_Link" "https://www.farnell.com/datasheets/3760989.pdf")
    (property "symbolName1" "CKSR_6-NP")
)
