(part "CRCW251215K0FKEG"
    (packageRef "RESC6332X70N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "CRCW251215K0FKEG")
    (property "Mouser_Part_Number" "71-CRCW2512-15K-E3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Dale/CRCW251215K0FKEG?qs=Z1AZHWO%2FsqI0c6vK0jJZww%3D%3D")
    (property "Arrow_Part_Number" "CRCW251215K0FKEG")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/crcw251215k0fkeg/vishay?region=nac")
    (property "Description" "VISHAY - CRCW251215K0FKEG - RESISTOR, THICK FILM CHIP, 15KOHM, 1W, 1%")
    (property "Datasheet_Link" "http://www.vishay.com/docs/20035/dcrcwe3.pdf")
    (property "symbolName1" "CRCW251215K0FKEG")
)
