(part "D22V0H1U2LP-7B"
    (packageRef "D22V0H1U2LP7B")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "D22V0H1U2LP-7B")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "ESD Suppressors / TVS Diodes General Protection PP X1-DFN1006-2 T&R 10K")
    (property "Datasheet_Link" "https://www.diodes.com/assets/Datasheets/D22V0H1U2LP.pdf")
    (property "symbolName1" "D22V0H1U2LP-7B")
)
