(part "TPS7A2030PDBVR"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "N/C") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS7A2030PDBVR")
    (property "Mouser_Part_Number" "595-TPS7A2030PDBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS7A2030PDBVR?qs=hd1VzrDQEGgZMtQinkbhYw%3D%3D")
    (property "Arrow_Part_Number" "TPS7A2030PDBVR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/tps7a2030pdbvr/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "LDO Voltage Regulators 300-mA, ultra-low-noise, low-IQ, low-dropout (LDO) linear regulator with high PSRR")
    (property "Datasheet_Link" "https://www.arrow.com/en/products/tps7a2030pdbvr/texas-instruments")
    (property "symbolName1" "TPS7A2030PDBVR")
)
