(part "NCM3S1212MC-R7"
    (packageRef "NCM3S1212MCR7")
    (interface
        (port "1" (symbPinId 1) (portName "-VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "+VIN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+VOUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "-VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "NCM3S1212MC-R7")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Surface Mount Isolated Module DC DC Converter 1 Output 12V 250mA 9V - 36V Input -40C ~ 105C  4-SMD Module")
    (property "Datasheet_Link" "https://pim.murata.com/asset/pim4/isolatedDCDCconverter/KDC_NCM3_PDF_ISOLATEDDCDCCONVERTER?lastModifiedDatetime=20250826165014")
    (property "symbolName1" "NCM3S1212MC-R7")
)
