(part "REF1933AIDDCR"
    (packageRef "SOT95P280X110-5N")
    (interface
        (port "1" (symbPinId 1) (portName "VBIAS") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType GROUND))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VIN") (portType INPUT))
        (port "5" (symbPinId 5) (portName "VREF") (portType INPUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "REF1933AIDDCR")
    (property "Mouser_Part_Number" "595-REF1933AIDDCR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/REF1933AIDDCR?qs=asCBFxFfL1SSAJuHGdYYcw%3D%3D")
    (property "Arrow_Part_Number" "REF1933AIDDCR")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ref1933aiddcr/texas-instruments?utm_currency=USD&region=nac")
    (property "Description" "Voltage References Dual Output Vref & Vref/2 Voltage Ref")
    (property "Datasheet_Link" "http://www.mouser.com/ds/2/405/ref1933-464431.pdf")
    (property "symbolName1" "REF1933AIDDCR")
)
