(part "STPS20200CTN"
    (packageRef "TO255P460X1020X1905-3P")
    (interface
        (port "1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "K") (portType INOUT))
        (port "3" (symbPinId 3) (portName "A2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "STPS20200CTN")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "STMicroelectronics 200V 30A, Dual Diode, 3-Pin TO-220AB STPS20200CTN")
    (property "Datasheet_Link" "http://www.st.com/web/en/resource/technical/document/datasheet/DM00079941.pdf")
    (property "symbolName1" "STPS20200CTN")
)
