(part "IPP111N15N3GXKSA1"
    (packageRef "TO254P457X1003X2115-3P")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "IPP111N15N3GXKSA1")
    (property "Mouser_Part_Number" "726-IPP111N15N3GXKSA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/IPP111N15N3GXKSA1?qs=OwbwYO03UsJO1bujDVMB%2Fw%3D%3D")
    (property "Arrow_Part_Number" "IPP111N15N3GXKSA1")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ipp111n15n3gxksa1/infineon-technologies-ag?region=europe")
    (property "Description" "MOSFET N-Ch 150V 83A TO220-3 OptiMOS 3")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/2/IPP111N15N3GXKSA1.pdf")
    (property "symbolName1" "IPP111N15N3GXKSA1")
)
