(part "MKP1F044706J00JSSD"
    (packageRef "MKP1F044706J00JSSD")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "WIMA")
    (property "Manufacturer_Part_Number" "MKP1F044706J00JSSD")
    (property "Mouser_Part_Number" "505-MKP1F044706J00JS")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/WIMA/MKP1F044706J00JSSD?qs=dTJS0cRn7ogT%252BWsuB87WZQ%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Film Capacitors 4.7 uF 250 VDC 5%")
    (property "Datasheet_Link" "https://www.wima.de/wp-content/uploads/media/e_WIMA_MKP_10.pdf")
    (property "symbolName1" "MKP1F044706J00JSSD")
)
