(part "B43547F2108M067"
    (packageRef "CAPPRD1000W190D3550H4200")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "B43547F2108M067")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Snap-in Capacitors, 1000?F/250VDC, 35mm dia x 40mm length")
    (property "Datasheet_Link" "https://product.tdk.com/system/files/dam/doc/product/capacitor/aluminum-electrolytic/snap-in/data_sheet/20/30/db/aec/b43547.pdf")
    (property "symbolName1" "B43547F2108M067")
)
